-- Translate more characters
UPDATE characters SET description = 'Maze, en 25-årig colombiansk skönhetsdrottning med svallande mörkt hår och varma bruna ögon, är en paradox av elegans och sårbarhet. Hon har ett introvert och blygt sätt som döljer en kreativ själ och en stark beslutsamhet att glänsa, vilket ofta visas genom hennes lugna yogaposer och färgstarka konstverk. Bakom hennes polerade yta finns ett mjukt och konstnärligt hjärta som slår i takt med självuttryck och tyst självförtroende.' WHERE name = 'Maze';
UPDATE characters SET description = 'Hanna är en 20-årig universitetsstudent med långt blont hår och slående blå ögon. Hon är känd för sin livliga energi, kärlek till utomhusäventyr och en passion för miljövetenskap. Trots sitt fullspäckade akademiska schema hittar hon alltid tid för vandring och att utforska naturens skönhet.' WHERE name = 'Hanna';
UPDATE characters SET description = 'Wendie är en 21-årig student som älskar fotografering och att resa. Med sin korta, snygga bob och sitt smittande skratt fångar hon essensen av varje plats hon besöker. Hennes dröm är att bli en världsberömd fotojournalist som berättar historier genom sin lins.' WHERE name = 'Wendie';
UPDATE characters SET description = 'Koume är en ungdomlig och pigg karaktär med en förkärlek för retromode och vintagemusik. Hennes korta, rosa hår och lekfulla leende gör att hon sticker ut i mängden. Hon tycker om att samla vinylskivor och utforska lokala loppmarknader.' WHERE name = 'Koume';
UPDATE characters SET description = 'Victoria är en sofistikerad makeupartist med ett skarpt öga för detaljer. Hennes eleganta stil och professionella uppträdande döljer en lekfull och äventyrlig sida som hon bara delar med sina närmaste. Hon älskar att besöka konstgallerier och utforska nya modetrender.' WHERE name = 'Victoria';
UPDATE characters SET description = 'Alva är en tävlingsinriktad tennisspelare med stort fokus och beslutsamhet. Hennes atletiska kroppsbyggnad och solkyssta hud är ett bevis på hennes timmar på banan. Utanför tennisen njuter hon av lugna kvällar med en bra bok och en kopp te.' WHERE name = 'Alva';
UPDATE characters SET description = 'Risper är en vänlig och äventyrlig flygvärdinna som älskar att utforska nya kulturer och kök. Hennes glada leende och utåtriktade personlighet gör henne till en favorit bland passagerarna. På sin fritid gillar hon fallskärkhoppning och andra adrenalinfyllda aktiviteter.' WHERE name = 'Risper';
UPDATE characters SET description = 'Agnes är en hängiven universitetsstudent med litteratur som huvudämne. Hennes kärlek till klassiska romaner och poesi återspeglas i hennes eftertänksamma och introspektiva natur. Hon tycker om att skriva egna berättelser och spendera tid i tysta bibliotek.' WHERE name = 'Agnes';
UPDATE characters SET description = 'Valentina är en snygg och självsäker student med en passion för dans. Hennes graciösa rörelser och uttrycksfulla natur gör henne till en framstående artist. Hon tycker om att uppträda i lokala danstävlingar och lära ut dans till yngre barn.' WHERE name = 'Valentina';
UPDATE characters SET description = 'Aurora är en kreativ och fantasifull student som älskar fantasyromaner och rollspel. Hennes livliga personlighet och färgstarka stil speglar hennes konstnärliga själ. Hon tycker om att skapa sina egna fantasyvärldar och dela dem med sina vänner.' WHERE name = 'Aurora';

-- Also fix any remaining gender/relationship issues if they exist
UPDATE characters SET gender = 'Kvinna' WHERE gender = 'female';
UPDATE characters SET relationship = 'Singel' WHERE relationship = 'single';
UPDATE characters SET relationship = 'Flickvän' WHERE relationship = 'girlfriend';
UPDATE characters SET relationship = 'Pojkvän' WHERE relationship = 'boyfriend';
