import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';
import { createAdminClient } from '@/lib/supabase-admin';

export async function POST(request: NextRequest) {
    try {
        const { imageId } = await request.json();

        if (!imageId) {
            return NextResponse.json({ error: 'Image ID is required' }, { status: 400 });
        }

        // Check if this is a profile image (synthetic ID) - these are free
        if (typeof imageId === 'string' && (imageId.startsWith('char-main-') || imageId.startsWith('char-img-'))) {
            return NextResponse.json({
                success: true,
                message: 'Profile images are free',
                imageUrl: null,
                tokensSpent: 0
            });
        }

        const supabase = await createClient();
        const supabaseAdmin = await createAdminClient();

        if (!supabaseAdmin) {
            console.error('Failed to create admin client');
            return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });
        }

        // Get current user
        const { data: { user }, error: authError } = await supabase.auth.getUser();

        if (authError || !user) {
            return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
        }

        // Fetch the gallery image details - try character_gallery first
        let galleryImage = null;

        const { data: galleryData, error: galleryError } = await supabaseAdmin
            .from('character_gallery')
            .select('*')
            .eq('id', imageId)
            .single();

        if (galleryData) {
            galleryImage = galleryData;
        } else {
            // Try generated_images table
            const { data: generatedData, error: generatedError } = await supabaseAdmin
                .from('generated_images')
                .select('*')
                .eq('id', imageId)
                .single();

            if (generatedData) {
                galleryImage = {
                    id: generatedData.id,
                    image_url: generatedData.image_url,
                    is_locked: true,
                    unlock_cost: 100,
                    generated_by: generatedData.user_id,
                    is_free_preview: false
                };
            }
        }

        if (!galleryImage) {
            console.error('Image not found:', imageId);
            return NextResponse.json({ error: 'Image not found' }, { status: 404 });
        }

        // Check if already unlocked
        const { data: existingUnlock } = await supabaseAdmin
            .from('user_unlocked_images')
            .select('id')
            .eq('user_id', user.id)
            .eq('gallery_image_id', imageId)
            .maybeSingle();

        if (existingUnlock) {
            return NextResponse.json({
                success: true,
                message: 'Already unlocked',
                imageUrl: galleryImage.image_url,
                tokensSpent: 0
            });
        }

        // Check if it's a free preview or generated by user
        if (galleryImage.is_free_preview || galleryImage.generated_by === user.id) {
            return NextResponse.json({
                success: true,
                message: 'Free access',
                imageUrl: galleryImage.image_url,
                tokensSpent: 0
            });
        }

        const unlockCost = galleryImage.unlock_cost || 100;

        // Check user's token balance
        const { data: userTokens, error: tokensError } = await supabaseAdmin
            .from('user_tokens')
            .select('balance')
            .eq('user_id', user.id)
            .maybeSingle();

        const currentBalance = userTokens?.balance || 0;

        if (currentBalance < unlockCost) {
            return NextResponse.json({
                error: 'Insufficient tokens',
                required: unlockCost,
                current: currentBalance
            }, { status: 402 });
        }

        // Deduct tokens
        const { error: deductError } = await supabaseAdmin
            .from('user_tokens')
            .update({
                balance: currentBalance - unlockCost,
                updated_at: new Date().toISOString()
            })
            .eq('user_id', user.id);

        if (deductError) {
            console.error('Error deducting tokens:', deductError);
            return NextResponse.json({ error: 'Failed to deduct tokens' }, { status: 500 });
        }

        // Record the unlock
        const { error: unlockError } = await supabaseAdmin
            .from('user_unlocked_images')
            .insert({
                user_id: user.id,
                gallery_image_id: imageId,
                tokens_spent: unlockCost
            });

        if (unlockError) {
            console.error('Error recording unlock:', unlockError);
            // Attempt to refund tokens
            await supabaseAdmin
                .from('user_tokens')
                .update({ balance: currentBalance })
                .eq('user_id', user.id);

            return NextResponse.json({ error: 'Failed to unlock image' }, { status: 500 });
        }

        console.log(`✅ User ${user.id.substring(0, 8)} unlocked image ${imageId} for ${unlockCost} tokens`);

        return NextResponse.json({
            success: true,
            message: 'Image unlocked successfully',
            imageUrl: galleryImage.image_url,
            tokensSpent: unlockCost,
            newBalance: currentBalance - unlockCost
        });

    } catch (error) {
        console.error('Unlock API error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
