import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';

export async function POST(request: NextRequest) {
    try {
        const { imageId } = await request.json();

        if (!imageId) {
            return NextResponse.json({ error: 'Image ID is required' }, { status: 400 });
        }

        const supabase = await createClient();

        // Get current user
        const { data: { user }, error: authError } = await supabase.auth.getUser();

        if (authError || !user) {
            return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
        }

        // Fetch the gallery image details
        const { data: galleryImage, error: imageError } = await supabase
            .from('character_gallery')
            .select('*')
            .eq('id', imageId)
            .single();

        if (imageError || !galleryImage) {
            return NextResponse.json({ error: 'Image not found' }, { status: 404 });
        }

        // Check if already unlocked
        const { data: existingUnlock } = await supabase
            .from('user_unlocked_images')
            .select('id')
            .eq('user_id', user.id)
            .eq('gallery_image_id', imageId)
            .single();

        if (existingUnlock) {
            return NextResponse.json({
                success: true,
                message: 'Already unlocked',
                imageUrl: galleryImage.image_url
            });
        }

        // Check if it's a free preview or generated by user
        if (galleryImage.is_free_preview || galleryImage.generated_by === user.id) {
            return NextResponse.json({
                success: true,
                message: 'Free access',
                imageUrl: galleryImage.image_url
            });
        }

        const unlockCost = galleryImage.unlock_cost || 100;

        // Check user's token balance
        const { data: userTokens, error: tokensError } = await supabase
            .from('user_tokens')
            .select('balance')
            .eq('user_id', user.id)
            .single();

        const currentBalance = userTokens?.balance || 0;

        if (currentBalance < unlockCost) {
            return NextResponse.json({
                error: 'Insufficient tokens',
                required: unlockCost,
                current: currentBalance
            }, { status: 402 });
        }

        // Deduct tokens
        const { error: deductError } = await supabase
            .from('user_tokens')
            .update({
                balance: currentBalance - unlockCost,
                updated_at: new Date().toISOString()
            })
            .eq('user_id', user.id);

        if (deductError) {
            console.error('Error deducting tokens:', deductError);
            return NextResponse.json({ error: 'Failed to deduct tokens' }, { status: 500 });
        }

        // Record the unlock
        const { error: unlockError } = await supabase
            .from('user_unlocked_images')
            .insert({
                user_id: user.id,
                gallery_image_id: imageId,
                tokens_spent: unlockCost
            });

        if (unlockError) {
            console.error('Error recording unlock:', unlockError);
            // Attempt to refund tokens
            await supabase
                .from('user_tokens')
                .update({ balance: currentBalance })
                .eq('user_id', user.id);

            return NextResponse.json({ error: 'Failed to unlock image' }, { status: 500 });
        }

        return NextResponse.json({
            success: true,
            message: 'Image unlocked successfully',
            imageUrl: galleryImage.image_url,
            tokensSpent: unlockCost,
            newBalance: currentBalance - unlockCost
        });

    } catch (error) {
        console.error('Unlock API error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
